# Generated by Django 5.2.17 on 2026-08-06 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.PositiveIntegerField()),
                ("end", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="dashboard.dataset",
                    ),
                ),
            ],
            options={
                "ordering": ["start", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SubSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("przygotowanie", "Przygotowanie"),
                            ("przymierzanie", "Przymierzanie"),
                            ("uderzenie", "Uderzenie"),
                            ("po_uderzeniu", "Po uderzeniu"),
                        ],
                        max_length=32,
                    ),
                ),
                ("start", models.PositiveIntegerField()),
                ("end", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsegments",
                        to="dashboard.segment",
                    ),
                ),
            ],
            options={
                "ordering": ["start", "pk"],
                "unique_together": {("segment", "phase")},
            },
        ),
    ]
