"""
Django settings for accur8pool_web project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-mwa$#!^0c1ic23wstx607fe_a*k39+e5$5u%m99=)$l^-8x4w&"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "accur8pool.pl",
    "www.accur8pool.pl",
    "127.0.0.1",
    "localhost",
]

CSRF_TRUSTED_ORIGINS = [
    "http://accur8pool.pl",
    "http://www.accur8pool.pl",
    'https://accur8pool.pl',
    'https://www.accur8pool.pl',
]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Dane użytkowników leżą w dwóch równoległych drzewach o tej samej
# strukturze (<dir>/<user_id>/<filename>.csv):
#   raw_data      — plik dokładnie taki, jaki przyszedł z uploadu; kopia
#                   źródłowa, z której da się przygotowanie powtórzyć,
#   prepared_data — ten sam plik po transform_raw_df (filtry, magnitudy,
#                   jerk, roll/pitch), liczony w trakcie uploadu.
# APLIKACJA CZYTA WYŁĄCZNIE Z prepared_data. Upload, któremu nie udało się
# przygotować danych, jest odrzucany i nie zostawia po sobie ani pliku
# w raw_data, ani wpisu w bazie — nie ma więc zestawów „widocznych, ale
# nie do otwarcia”.
# Ta sama nazwa pliku w obu katalogach wiąże wersję surową z przygotowaną,
# więc nie trzeba trzymać drugiej ścieżki w bazie.
ACCUR8POOL_DATA_DIR = BASE_DIR / "new_data" / "raw_data"
ACCUR8POOL_PREPARED_DATA_DIR = BASE_DIR / "new_data" / "prepared_data"
AUTH_PASSWORD_VALIDATORS = []
LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/dashboard'
LOGOUT_REDIRECT_URL = '/login'
# Application definition
STATIC_URL = "static/"
CSRF_COOKIE_HTTPONLY = False
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'account',
    'dashboard'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "accur8pool_web.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "accur8pool_web.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
